// The 200 most frequently used Chinese characters, most common first
// (from Jun Da's Modern Chinese Character Frequency List).
const TOP_200 = Array.from(
  "的一是不了在人有我他这个们中来上大为和国地到以说时要就出会可也你对生能而子那得于着下自之年过发后作里" +
  "用道行所然家种事成方多经么去法学如都同现当没动面起看定天分还进好小部其些主样理心她本前开但因只从想实" +
  "日军者意无力它与长把机十民第公此已工使情明性知全三又关点正业外将两高间由问很最重并物手应战向头文体政" +
  "美相见被利什二等产或新己制身果加西斯月话合回特代内信表化老给世位次度门任常先海通教儿原东声提立及比员"
);

// Character dictionary used for the breakdown: character → [pinyin, meaning].
// Characters with more than one common pronunciation list both.
const CHARS = {
  "你": ["nǐ", "you"],
  "好": ["hǎo", "good"],
  "谢": ["xiè", "to thank"],
  "朋": ["péng", "friend"],
  "友": ["yǒu", "friend"],
  "喜": ["xǐ", "happy; to like"],
  "欢": ["huān", "joyful"],
  "学": ["xué", "to study"],
  "习": ["xí", "to practice"],
  "工": ["gōng", "work"],
  "作": ["zuò", "to do; to make"],
  "时": ["shí", "time; hour"],
  "间": ["jiān", "between; room"],
  "今": ["jīn", "now; today"],
  "天": ["tiān", "day; sky"],
  "吃": ["chī", "to eat"],
  "饭": ["fàn", "cooked rice; meal"],
  "知": ["zhī", "to know"],
  "道": ["dào", "road; way; to say"],
  "高": ["gāo", "tall; high"],
  "兴": ["xìng / xīng", "interest, excitement; (xīng) to rise"],
  "明": ["míng", "bright; clear"],
  "白": ["bái", "white; clear"],
  "的": ["de / dí", "possessive particle ('s); (dí) true, real"],
  "确": ["què", "certain; true"],
  "一": ["yī", "one"],
  "起": ["qǐ", "to rise; to start"],
  "但": ["dàn", "but"],
  "是": ["shì", "to be; yes"],
  "不": ["bù", "not; no"],
  "同": ["tóng", "same; together"],
  "了": ["le / liǎo", "marks a completed action; (liǎo) to finish, to understand"],
  "解": ["jiě", "to untie; to explain"],
  "现": ["xiàn", "now; to appear"],
  "在": ["zài", "at; in; to be present"],
  "人": ["rén", "person"],
  "民": ["mín", "the people; citizens"],
  "没": ["méi", "not (have)"],
  "有": ["yǒu", "to have; there is"],
  "我": ["wǒ", "I; me"],
  "们": ["men", "plural suffix for people"],
  "他": ["tā", "he; him"],
  "这": ["zhè", "this"],
  "样": ["yàng", "shape; manner; kind"],
  "个": ["gè", "general measure word; individual"],
  "性": ["xìng", "nature; character; gender"],
  "中": ["zhōng", "middle; China"],
  "国": ["guó", "country"],
  "后": ["hòu", "after; behind"],
  "来": ["lái", "to come"],
  "上": ["shàng", "above; up; previous"],
  "次": ["cì", "time (occurrence); next in order"],
  "大": ["dà", "big"],
  "家": ["jiā", "home; family"],
  "因": ["yīn", "cause; because"],
  "为": ["wèi / wéi", "for, because of; (wéi) to act as, to be"],
  "和": ["hé", "and; peace; harmony"],
  "平": ["píng", "flat; peaceful"],
  "地": ["dì / de", "earth, ground, place; (de) adverb particle"],
  "方": ["fāng", "square; direction; side"],
  "得": ["dé / de", "to get; (de) particle after verbs"],
  "到": ["dào", "to arrive; to reach"],
  "可": ["kě", "can; may"],
  "以": ["yǐ", "to use; by means of"],
  "说": ["shuō", "to speak; to say"],
  "话": ["huà", "speech; words"],
  "重": ["zhòng / chóng", "heavy, important; (chóng) again"],
  "要": ["yào", "to want; must; important"],
  "就": ["jiù", "just; then; exactly"],
  "出": ["chū", "to go out"],
  "发": ["fā", "to send out; to emit"],
  "开": ["kāi", "to open; to start"],
  "会": ["huì", "meeting; can; will"],
  "也": ["yě", "also"],
  "许": ["xǔ", "to allow; perhaps"],
  "生": ["shēng", "to be born; life; raw"],
  "日": ["rì", "sun; day"],
  "能": ["néng", "can; able"],
  "力": ["lì", "strength; power"],
  "而": ["ér", "and; but (connecting word)"],
  "且": ["qiě", "moreover"],
  "儿": ["ér", "child; son"],
  "子": ["zǐ / zi", "child; (zi) noun suffix"],
  "那": ["nà", "that"],
  "些": ["xiē", "some; a few"],
  "关": ["guān", "to close; relation"],
  "于": ["yú", "at; in; to"],
  "接": ["jiē", "to receive; to connect"],
  "着": ["zhe / zháo", "marks an ongoing action; (zháo) to touch, to catch"],
  "下": ["xià", "below; down; next"],
  "午": ["wǔ", "noon"],
  "自": ["zì", "self; from"],
  "己": ["jǐ", "oneself"],
  "之": ["zhī", "(literary) of; it"],
  "前": ["qián", "front; before"],
  "新": ["xīn", "new"],
  "年": ["nián", "year"],
  "过": ["guò", "to pass; to cross"],
  "去": ["qù", "to go"],
  "里": ["lǐ", "inside"],
  "面": ["miàn", "face; side; surface"],
  "对": ["duì", "correct; towards; opposite"],
  "使": ["shǐ", "to use; to make (someone do)"],
  "用": ["yòng", "to use"],
  "行": ["xíng / háng", "to walk, OK; (háng) row, business"],
  "动": ["dòng", "to move"],
  "所": ["suǒ", "place; that which"],
  "当": ["dāng", "to serve as; should; when"],
  "然": ["rán", "so; like that"],
  "各": ["gè", "each; every"],
  "种": ["zhǒng / zhòng", "kind, type; (zhòng) to plant"],
  "事": ["shì", "matter; thing"],
  "情": ["qíng", "feeling; situation"],
  "成": ["chéng", "to become; to succeed"],
  "功": ["gōng", "achievement; merit"],
  "多": ["duō", "many; much"],
  "少": ["shǎo", "few; little"],
  "已": ["yǐ", "already"],
  "经": ["jīng", "to pass through; classic text"],
  "什": ["shén", "what (in 什么)"],
  "么": ["me", "suffix (in 什么, 这么)"],
  "想": ["xiǎng", "to think; to want"],
  "法": ["fǎ", "method; law"],
  "如": ["rú", "if; like"],
  "果": ["guǒ", "fruit; result"],
  "首": ["shǒu", "head; first"],
  "都": ["dōu / dū", "all; (dū) capital city"],
  "看": ["kàn", "to look; to see"],
  "见": ["jiàn", "to see; to meet"],
  "定": ["dìng", "to decide; fixed"],
  "部": ["bù", "part; section"],
  "分": ["fēn / fèn", "to divide, minute; (fèn) part"],
  "还": ["hái / huán", "still, also; (huán) to return"],
  "进": ["jìn", "to enter; to advance"],
  "步": ["bù", "step"],
  "小": ["xiǎo", "small"],
  "心": ["xīn", "heart; mind"],
  "主": ["zhǔ", "main; master"],
  "理": ["lǐ", "reason; logic; to manage"],
  "由": ["yóu", "cause; from"],
  "身": ["shēn", "body"],
  "体": ["tǐ", "body; form"],
  "本": ["běn", "root; origin; measure word for books"],
  "只": ["zhǐ", "only"],
  "从": ["cóng", "from"],
  "其": ["qí", "its; that"],
  "实": ["shí", "real; true"],
  "军": ["jūn", "army; military"],
  "或": ["huò", "or"],
  "者": ["zhě", "one who (suffix)"],
  "意": ["yì", "meaning; idea"],
  "思": ["sī", "to think"],
  "无": ["wú", "without; none"],
  "聊": ["liáo", "to chat"],
  "它": ["tā", "it"],
  "参": ["cān", "to take part"],
  "与": ["yǔ / yù", "and, with; (yù) to take part in"],
  "长": ["cháng / zhǎng", "long; (zhǎng) to grow"],
  "把": ["bǎ", "to hold; grammar word that moves the object forward"],
  "握": ["wò", "to grasp"],
  "手": ["shǒu", "hand"],
  "机": ["jī", "machine; opportunity"],
  "十": ["shí", "ten"],
  "第": ["dì", "ordinal prefix (1st, 2nd…)"],
  "二": ["èr", "two"],
  "公": ["gōng", "public"],
  "司": ["sī", "to manage"],
  "此": ["cǐ", "this"],
  "安": ["ān", "peaceful; safe"],
  "全": ["quán", "complete; whole"],
  "三": ["sān", "three"],
  "又": ["yòu", "again; also"],
  "月": ["yuè", "moon; month"],
  "点": ["diǎn", "dot; point; o'clock"],
  "头": ["tóu", "head"],
  "正": ["zhèng", "straight; correct; just now"],
  "常": ["cháng", "often; normal"],
  "业": ["yè", "business; profession"],
  "外": ["wài", "outside"],
  "将": ["jiāng", "will; about to"],
  "两": ["liǎng", "two (of something)"],
  "问": ["wèn", "to ask"],
  "题": ["tí", "topic; question"],
  "很": ["hěn", "very"],
  "最": ["zuì", "most"],
  "近": ["jìn", "near"],
  "并": ["bìng", "and; also"],
  "物": ["wù", "thing; object"],
  "应": ["yīng", "should"],
  "该": ["gāi", "should; that"],
  "战": ["zhàn", "war; battle"],
  "争": ["zhēng", "to fight; to compete"],
  "向": ["xiàng", "direction; towards"],
  "文": ["wén", "writing; language; culture"],
  "政": ["zhèng", "politics"],
  "府": ["fǔ", "government office; mansion"],
  "美": ["měi", "beautiful; America"],
  "相": ["xiāng", "mutually; each other"],
  "信": ["xìn", "letter; to believe"],
  "再": ["zài", "again"],
  "被": ["bèi", "quilt; marks the passive voice"],
  "顺": ["shùn", "smooth; along"],
  "利": ["lì", "benefit; sharp"],
  "等": ["děng", "to wait; class; etc."],
  "待": ["dài", "to wait; to treat"],
  "产": ["chǎn", "to produce"],
  "制": ["zhì", "to make; system"],
  "度": ["dù", "degree; measure"],
  "加": ["jiā", "to add"],
  "油": ["yóu", "oil; gasoline"],
  "东": ["dōng", "east"],
  "西": ["xī", "west"],
  "斯": ["sī", "this (literary); used in foreign names"],
  "合": ["hé", "to fit; to combine"],
  "适": ["shì", "suitable"],
  "回": ["huí", "to return"],
  "特": ["tè", "special"],
  "别": ["bié", "other; don't"],
  "代": ["dài", "to replace; generation"],
  "表": ["biǎo", "to show; surface; watch"],
  "内": ["nèi", "inside"],
  "容": ["róng", "to hold; appearance"],
  "化": ["huà", "to change; -ize"],
  "老": ["lǎo", "old"],
  "师": ["shī", "teacher; master"],
  "送": ["sòng", "to give; to send"],
  "给": ["gěi", "to give; for"],
  "世": ["shì", "world; generation"],
  "界": ["jiè", "boundary"],
  "座": ["zuò", "seat; measure word for buildings"],
  "位": ["wèi", "position; seat"],
  "门": ["mén", "door; gate"],
  "口": ["kǒu", "mouth; opening"],
  "任": ["rèn", "to appoint; any"],
  "何": ["hé", "what; which"],
  "先": ["xiān", "first"],
  "海": ["hǎi", "sea"],
  "交": ["jiāo", "to hand over; to cross"],
  "通": ["tōng", "to go through"],
  "教": ["jiào / jiāo", "teaching; (jiāo) to teach"],
  "室": ["shì", "room"],
  "原": ["yuán", "original"],
  "声": ["shēng", "sound; voice"],
  "音": ["yīn", "sound"],
  "提": ["tí", "to lift; to raise"],
  "立": ["lì", "to stand"],
  "刻": ["kè", "moment; quarter hour; to carve"],
  "及": ["jí", "to reach; in time"],
  "比": ["bǐ", "to compare"],
  "较": ["jiào", "relatively; to compare"],
  "演": ["yǎn", "to act; to perform"],
  "员": ["yuán", "person; member"],
  "她": ["tā", "she; her"]
};
