// The 200 most frequently used Chinese characters, most common first
// (from Jun Da's Modern Chinese Character Frequency List).
const TOP_200 = Array.from(
  "的一是不了在人有我他这个们中来上大为和国地到以说时要就出会可也你对生能而子那得于着下自之年过发后作里" +
  "用道行所然家种事成方多经么去法学如都同现当没动面起看定天分还进好小部其些主样理心她本前开但因只从想实" +
  "日军者意无力它与长把机十民第公此已工使情明性知全三又关点正业外将两高间由问很最重并物手应战向头文体政" +
  "美相见被利什二等产或新己制身果加西斯月话合回特代内信表化老给世位次度门任常先海通教儿原东声提立及比员"
);

// Character dictionary used for the breakdown: character → [pinyin, meaning].
// Characters with more than one common pronunciation list both.
const CHARS = {
  "你": ["nǐ", "you"],
  "好": ["hǎo", "good"],
  "谢": ["xiè", "to thank"],
  "朋": ["péng", "friend"],
  "友": ["yǒu", "friend"],
  "喜": ["xǐ", "happy; to like"],
  "欢": ["huān", "joyful"],
  "学": ["xué", "to study"],
  "习": ["xí", "to practice"],
  "工": ["gōng", "work"],
  "作": ["zuò", "to do; to make"],
  "时": ["shí", "time; hour"],
  "间": ["jiān", "between; room"],
  "今": ["jīn", "now; today"],
  "天": ["tiān", "day; sky"],
  "吃": ["chī", "to eat"],
  "饭": ["fàn", "cooked rice; meal"],
  "知": ["zhī", "to know"],
  "道": ["dào", "road; way; to say"],
  "高": ["gāo", "tall; high"],
  "兴": ["xìng / xīng", "interest, excitement; (xīng) to rise"],
  "明": ["míng", "bright; clear"],
  "白": ["bái", "white; clear"],
  "的": ["de / dí", "possessive particle ('s); (dí) true, real"],
  "确": ["què", "certain; true"],
  "一": ["yī", "one"],
  "起": ["qǐ", "to rise; to start"],
  "但": ["dàn", "but"],
  "是": ["shì", "to be; yes"],
  "不": ["bù", "not; no"],
  "同": ["tóng", "same; together"],
  "了": ["le / liǎo", "marks a completed action; (liǎo) to finish, to understand"],
  "解": ["jiě", "to untie; to explain"],
  "现": ["xiàn", "now; to appear"],
  "在": ["zài", "at; in; to be present"],
  "人": ["rén", "person"],
  "民": ["mín", "the people; citizens"],
  "没": ["méi", "not (have)"],
  "有": ["yǒu", "to have; there is"],
  "我": ["wǒ", "I; me"],
  "们": ["men", "plural suffix for people"],
  "他": ["tā", "he; him"],
  "这": ["zhè", "this"],
  "样": ["yàng", "shape; manner; kind"],
  "个": ["gè", "general measure word; individual"],
  "性": ["xìng", "nature; character; gender"],
  "中": ["zhōng", "middle; China"],
  "国": ["guó", "country"],
  "后": ["hòu", "after; behind"],
  "来": ["lái", "to come"],
  "上": ["shàng", "above; up; previous"],
  "次": ["cì", "time (occurrence); next in order"],
  "大": ["dà", "big"],
  "家": ["jiā", "home; family"],
  "因": ["yīn", "cause; because"],
  "为": ["wèi / wéi", "for, because of; (wéi) to act as, to be"],
  "和": ["hé", "and; peace; harmony"],
  "平": ["píng", "flat; peaceful"],
  "地": ["dì / de", "earth, ground, place; (de) adverb particle"],
  "方": ["fāng", "square; direction; side"],
  "得": ["dé / de", "to get; (de) particle after verbs"],
  "到": ["dào", "to arrive; to reach"],
  "可": ["kě", "can; may"],
  "以": ["yǐ", "to use; by means of"],
  "说": ["shuō", "to speak; to say"],
  "话": ["huà", "speech; words"],
  "重": ["zhòng / chóng", "heavy, important; (chóng) again"],
  "要": ["yào", "to want; must; important"],
  "就": ["jiù", "just; then; exactly"],
  "出": ["chū", "to go out"],
  "发": ["fā", "to send out; to emit"],
  "开": ["kāi", "to open; to start"],
  "会": ["huì", "meeting; can; will"],
  "也": ["yě", "also"],
  "许": ["xǔ", "to allow; perhaps"],
  "生": ["shēng", "to be born; life; raw"],
  "日": ["rì", "sun; day"],
  "能": ["néng", "can; able"],
  "力": ["lì", "strength; power"],
  "而": ["ér", "and; but (connecting word)"],
  "且": ["qiě", "moreover"],
  "儿": ["ér", "child; son"],
  "子": ["zǐ / zi", "child; (zi) noun suffix"],
  "那": ["nà", "that"],
  "些": ["xiē", "some; a few"],
  "关": ["guān", "to close; relation"],
  "于": ["yú", "at; in; to"],
  "接": ["jiē", "to receive; to connect"],
  "着": ["zhe / zháo", "marks an ongoing action; (zháo) to touch, to catch"],
  "下": ["xià", "below; down; next"],
  "午": ["wǔ", "noon"],
  "自": ["zì", "self; from"],
  "己": ["jǐ", "oneself"],
  "之": ["zhī", "(literary) of; it"],
  "前": ["qián", "front; before"],
  "新": ["xīn", "new"],
  "年": ["nián", "year"],
  "过": ["guò", "to pass; to cross"],
  "去": ["qù", "to go"],
  "里": ["lǐ", "inside"],
  "面": ["miàn", "face; side; surface"],
  "对": ["duì", "correct; towards; opposite"],
  "使": ["shǐ", "to use; to make (someone do)"],
  "用": ["yòng", "to use"],
  "行": ["xíng / háng", "to walk, OK; (háng) row, business"],
  "动": ["dòng", "to move"],
  "所": ["suǒ", "place; that which"],
  "当": ["dāng", "to serve as; should; when"],
  "然": ["rán", "so; like that"],
  "各": ["gè", "each; every"],
  "种": ["zhǒng / zhòng", "kind, type; (zhòng) to plant"],
  "事": ["shì", "matter; thing"],
  "情": ["qíng", "feeling; situation"],
  "成": ["chéng", "to become; to succeed"],
  "功": ["gōng", "achievement; merit"],
  "多": ["duō", "many; much"],
  "少": ["shǎo", "few; little"],
  "已": ["yǐ", "already"],
  "经": ["jīng", "to pass through; classic text"],
  "什": ["shén", "what (in 什么)"],
  "么": ["me", "suffix (in 什么, 这么)"],
  "想": ["xiǎng", "to think; to want"],
  "法": ["fǎ", "method; law"],
  "如": ["rú", "if; like"],
  "果": ["guǒ", "fruit; result"],
  "首": ["shǒu", "head; first"],
  "都": ["dōu / dū", "all; (dū) capital city"],
  "看": ["kàn", "to look; to see"],
  "见": ["jiàn", "to see; to meet"],
  "定": ["dìng", "to decide; fixed"],
  "部": ["bù", "part; section"],
  "分": ["fēn / fèn", "to divide, minute; (fèn) part"],
  "还": ["hái / huán", "still, also; (huán) to return"],
  "进": ["jìn", "to enter; to advance"],
  "步": ["bù", "step"],
  "小": ["xiǎo", "small"],
  "心": ["xīn", "heart; mind"],
  "主": ["zhǔ", "main; master"],
  "理": ["lǐ", "reason; logic; to manage"],
  "由": ["yóu", "cause; from"],
  "身": ["shēn", "body"],
  "体": ["tǐ", "body; form"],
  "本": ["běn", "root; origin; measure word for books"],
  "只": ["zhǐ", "only"],
  "从": ["cóng", "from"],
  "其": ["qí", "its; that"],
  "实": ["shí", "real; true"],
  "军": ["jūn", "army; military"],
  "或": ["huò", "or"],
  "者": ["zhě", "one who (suffix)"],
  "意": ["yì", "meaning; idea"],
  "思": ["sī", "to think"],
  "无": ["wú", "without; none"],
  "聊": ["liáo", "to chat"],
  "它": ["tā", "it"],
  "参": ["cān", "to take part"],
  "与": ["yǔ / yù", "and, with; (yù) to take part in"],
  "长": ["cháng / zhǎng", "long; (zhǎng) to grow"],
  "把": ["bǎ", "to hold; grammar word that moves the object forward"],
  "握": ["wò", "to grasp"],
  "手": ["shǒu", "hand"],
  "机": ["jī", "machine; opportunity"],
  "十": ["shí", "ten"],
  "第": ["dì", "ordinal prefix (1st, 2nd…)"],
  "二": ["èr", "two"],
  "公": ["gōng", "public"],
  "司": ["sī", "to manage"],
  "此": ["cǐ", "this"],
  "安": ["ān", "peaceful; safe"],
  "全": ["quán", "complete; whole"],
  "三": ["sān", "three"],
  "又": ["yòu", "again; also"],
  "月": ["yuè", "moon; month"],
  "点": ["diǎn", "dot; point; o'clock"],
  "头": ["tóu", "head"],
  "正": ["zhèng", "straight; correct; just now"],
  "常": ["cháng", "often; normal"],
  "业": ["yè", "business; profession"],
  "外": ["wài", "outside"],
  "将": ["jiāng", "will; about to"],
  "两": ["liǎng", "two (of something)"],
  "问": ["wèn", "to ask"],
  "题": ["tí", "topic; question"],
  "很": ["hěn", "very"],
  "最": ["zuì", "most"],
  "近": ["jìn", "near"],
  "并": ["bìng", "and; also"],
  "物": ["wù", "thing; object"],
  "应": ["yīng", "should"],
  "该": ["gāi", "should; that"],
  "战": ["zhàn", "war; battle"],
  "争": ["zhēng", "to fight; to compete"],
  "向": ["xiàng", "direction; towards"],
  "文": ["wén", "writing; language; culture"],
  "政": ["zhèng", "politics"],
  "府": ["fǔ", "government office; mansion"],
  "美": ["měi", "beautiful; America"],
  "相": ["xiāng", "mutually; each other"],
  "信": ["xìn", "letter; to believe"],
  "再": ["zài", "again"],
  "被": ["bèi", "quilt; marks the passive voice"],
  "顺": ["shùn", "smooth; along"],
  "利": ["lì", "benefit; sharp"],
  "等": ["děng", "to wait; class; etc."],
  "待": ["dài", "to wait; to treat"],
  "产": ["chǎn", "to produce"],
  "制": ["zhì", "to make; system"],
  "度": ["dù", "degree; measure"],
  "加": ["jiā", "to add"],
  "油": ["yóu", "oil; gasoline"],
  "东": ["dōng", "east"],
  "西": ["xī", "west"],
  "斯": ["sī", "this (literary); used in foreign names"],
  "合": ["hé", "to fit; to combine"],
  "适": ["shì", "suitable"],
  "回": ["huí", "to return"],
  "特": ["tè", "special"],
  "别": ["bié", "other; don't"],
  "代": ["dài", "to replace; generation"],
  "表": ["biǎo", "to show; surface; watch"],
  "内": ["nèi", "inside"],
  "容": ["róng", "to hold; appearance"],
  "化": ["huà", "to change; -ize"],
  "老": ["lǎo", "old"],
  "师": ["shī", "teacher; master"],
  "送": ["sòng", "to give; to send"],
  "给": ["gěi", "to give; for"],
  "世": ["shì", "world; generation"],
  "界": ["jiè", "boundary"],
  "座": ["zuò", "seat; measure word for buildings"],
  "位": ["wèi", "position; seat"],
  "门": ["mén", "door; gate"],
  "口": ["kǒu", "mouth; opening"],
  "任": ["rèn", "to appoint; any"],
  "何": ["hé", "what; which"],
  "先": ["xiān", "first"],
  "海": ["hǎi", "sea"],
  "交": ["jiāo", "to hand over; to cross"],
  "通": ["tōng", "to go through"],
  "教": ["jiào / jiāo", "teaching; (jiāo) to teach"],
  "室": ["shì", "room"],
  "原": ["yuán", "original"],
  "声": ["shēng", "sound; voice"],
  "音": ["yīn", "sound"],
  "提": ["tí", "to lift; to raise"],
  "立": ["lì", "to stand"],
  "刻": ["kè", "moment; quarter hour; to carve"],
  "及": ["jí", "to reach; in time"],
  "比": ["bǐ", "to compare"],
  "较": ["jiào", "relatively; to compare"],
  "演": ["yǎn", "to act; to perform"],
  "员": ["yuán", "person; member"],
  "她": ["tā", "she; her"],

  // Characters used by the top-400 phrases (phrases-common.js)
  "丈": ["zhàng", "husband; elder (also a unit of length)"],
  "久": ["jiǔ", "long (time)"],
  "亡": ["wáng", "to die; to perish"],
  "亮": ["liàng", "bright"],
  "亲": ["qīn", "parent; relative; dear; to kiss"],
  "休": ["xiū", "to rest"],
  "伙": ["huǒ", "companion; partner"],
  "伤": ["shāng", "wound; to hurt"],
  "住": ["zhù", "to live; to stay; (after verbs) firmly"],
  "保": ["bǎo", "to protect; to keep"],
  "候": ["hòu", "to wait; time; season"],
  "做": ["zuò", "to do; to make"],
  "停": ["tíng", "to stop"],
  "像": ["xiàng", "to resemble; like"],
  "兄": ["xiōng", "older brother"],
  "入": ["rù", "to enter"],
  "决": ["jué", "to decide; definitely"],
  "况": ["kuàng", "situation; moreover"],
  "准": ["zhǔn", "accurate; to allow"],
  "几": ["jǐ", "how many; a few"],
  "切": ["qiè / qiē", "all, close to; (qiē) to cut"],
  "划": ["huà / huá", "to plan, to mark; (huá) to row"],
  "刚": ["gāng", "just; firm"],
  "办": ["bàn", "to do; to handle"],
  "务": ["wù", "affair; task"],
  "助": ["zhù", "to help"],
  "努": ["nǔ", "to exert (effort)"],
  "医": ["yī", "medicine; doctor"],
  "单": ["dān", "single; simple; list"],
  "危": ["wēi", "danger"],
  "即": ["jí", "namely; even; immediately"],
  "厌": ["yàn", "to dislike; to be fed up"],
  "受": ["shòu", "to receive; to bear"],
  "变": ["biàn", "to change"],
  "名": ["míng", "name; famous"],
  "否": ["fǒu", "no; not"],
  "听": ["tīng", "to listen; to hear"],
  "告": ["gào", "to tell; to inform"],
  "命": ["mìng", "life; fate; order"],
  "咱": ["zán", "we (including you)"],
  "哥": ["gē", "older brother"],
  "哪": ["nǎ", "which; where"],
  "唯": ["wéi", "only"],
  "嘛": ["ma", "particle (obviously; come on)"],
  "嘴": ["zuǐ", "mouth"],
  "器": ["qì", "tool; device"],
  "坐": ["zuò", "to sit; to ride (a vehicle)"],
  "士": ["shì", "scholar; person (polite)"],
  "处": ["chǔ / chù", "to handle; (chù) place"],
  "备": ["bèi", "to prepare"],
  "够": ["gòu", "enough"],
  "太": ["tài", "too; very"],
  "夫": ["fū", "husband; man"],
  "失": ["shī", "to lose"],
  "奇": ["qí", "strange; rare"],
  "女": ["nǚ", "woman; female"],
  "妈": ["mā", "mom"],
  "妻": ["qī", "wife"],
  "始": ["shǐ", "to begin"],
  "姐": ["jiě", "older sister"],
  "婆": ["pó", "old woman; mother-in-law"],
  "婚": ["hūn", "marriage"],
  "字": ["zì", "character; word"],
  "存": ["cún", "to exist; to store"],
  "孩": ["hái", "child"],
  "完": ["wán", "to finish; complete"],
  "官": ["guān", "official; officer"],
  "宝": ["bǎo", "treasure; precious"],
  "害": ["hài", "harm; to cause"],
  "密": ["mì", "secret; dense"],
  "察": ["chá", "to examine; to inspect"],
  "希": ["xī", "to hope; rare"],
  "帝": ["dì", "emperor; god"],
  "带": ["dài", "to bring; belt"],
  "帮": ["bāng", "to help"],
  "干": ["gàn / gān", "to do; (gān) dry"],
  "底": ["dǐ", "bottom; base"],
  "弃": ["qì", "to abandon"],
  "式": ["shì", "style; form"],
  "弟": ["dì", "younger brother"],
  "影": ["yǐng", "shadow; image; film"],
  "律": ["lǜ", "law; rule"],
  "必": ["bì", "must; certainly"],
  "忙": ["máng", "busy"],
  "快": ["kuài", "fast; happy"],
  "怎": ["zěn", "how"],
  "怕": ["pà", "to fear"],
  "怪": ["guài", "strange; to blame"],
  "总": ["zǒng", "always; total; chief"],
  "息": ["xī", "breath; news; to rest"],
  "感": ["gǎn", "to feel; feeling"],
  "愿": ["yuàn", "to wish; willing"],
  "戏": ["xì", "play; drama; game"],
  "房": ["fáng", "house; room"],
  "才": ["cái", "only then; talent"],
  "打": ["dǎ", "to hit; to do (many actions: call, play…)"],
  "托": ["tuō", "to entrust; to support"],
  "找": ["zhǎo", "to look for"],
  "抓": ["zhuā", "to grab; to catch"],
  "护": ["hù", "to protect"],
  "抱": ["bào", "to hug; to hold"],
  "担": ["dān", "to carry; to undertake"],
  "拜": ["bài", "to pay respect; to visit"],
  "择": ["zé", "to choose"],
  "持": ["chí", "to hold; to keep"],
  "控": ["kòng", "to control"],
  "收": ["shōu", "to receive; to collect"],
  "改": ["gǎi", "to change; to correct"],
  "放": ["fàng", "to put; to release"],
  "故": ["gù", "old; reason; therefore"],
  "整": ["zhěng", "whole; to tidy"],
  "早": ["zǎo", "early; morning"],
  "易": ["yì", "easy; to change"],
  "昨": ["zuó", "yesterday"],
  "晚": ["wǎn", "evening; late"],
  "更": ["gèng", "more; even more"],
  "曾": ["céng", "once; already"],
  "服": ["fú", "clothes; to serve; to obey"],
  "望": ["wàng", "to look; to hope"],
  "束": ["shù", "to bind; bundle"],
  "查": ["chá", "to check; to investigate"],
  "校": ["xiào", "school"],
  "根": ["gēn", "root"],
  "楚": ["chǔ", "clear; pain"],
  "概": ["gài", "general; approximate"],
  "歉": ["qiàn", "apology"],
  "止": ["zhǐ", "to stop"],
  "武": ["wǔ", "martial; military"],
  "死": ["sǐ", "to die; dead"],
  "母": ["mǔ", "mother"],
  "每": ["měi", "every; each"],
  "永": ["yǒng", "forever"],
  "求": ["qiú", "to request; to seek"],
  "注": ["zhù", "to pour; to note"],
  "活": ["huó", "to live; alive"],
  "消": ["xiāo", "to disappear; news"],
  "清": ["qīng", "clear; clean"],
  "游": ["yóu", "to swim; to travel; to play"],
  "漂": ["piào / piāo", "pretty (in 漂亮); (piāo) to float"],
  "烦": ["fán", "annoyed; to bother"],
  "照": ["zhào", "to shine; to take (a photo); to look after"],
  "爱": ["ài", "love; to love"],
  "父": ["fù", "father"],
  "爸": ["bà", "dad"],
  "片": ["piàn", "slice; piece; film"],
  "甚": ["shèn", "very; even more"],
  "电": ["diàn", "electricity"],
  "男": ["nán", "man; male"],
  "留": ["liú", "to stay; to keep"],
  "直": ["zhí", "straight; directly"],
  "真": ["zhēn", "real; really"],
  "眼": ["yǎn", "eye"],
  "睛": ["jīng", "eyeball"],
  "离": ["lí", "to leave; away from"],
  "秘": ["mì", "secret"],
  "突": ["tū", "sudden; to break through"],
  "答": ["dá", "to answer"],
  "简": ["jiǎn", "simple"],
  "算": ["suàn", "to calculate; to count as"],
  "管": ["guǎn", "to manage; to care about; tube"],
  "类": ["lèi", "kind; type"],
  "糕": ["gāo", "cake"],
  "糟": ["zāo", "messy; bad"],
  "系": ["xì", "system; to relate to"],
  "终": ["zhōng", "end; finally"],
  "结": ["jié", "to tie; to form; result"],
  "绝": ["jué", "absolutely; to cut off"],
  "统": ["tǒng", "to unite; system"],
  "继": ["jì", "to continue"],
  "续": ["xù", "to continue"],
  "翻": ["fān", "to turn over; to translate"],
  "肯": ["kěn", "to be willing"],
  "至": ["zhì", "to; until; most"],
  "虽": ["suī", "although"],
  "衣": ["yī", "clothes"],
  "觉": ["jué / jiào", "to feel; (jiào) sleep"],
  "警": ["jǐng", "to warn; police"],
  "计": ["jì", "to count; plan"],
  "认": ["rèn", "to recognize; to admit"],
  "讨": ["tǎo", "to discuss; to ask for"],
  "记": ["jì", "to remember; to record"],
  "证": ["zhèng", "proof; certificate"],
  "识": ["shí", "to know; knowledge"],
  "诉": ["sù", "to tell; to complain"],
  "译": ["yì", "to translate"],
  "调": ["diào / tiáo", "to transfer, tone; (tiáo) to adjust"],
  "谈": ["tán", "to talk"],
  "贝": ["bèi", "shell; treasure"],
  "赛": ["sài", "competition; race"],
  "趣": ["qù", "interest; fun"],
  "轻": ["qīng", "light; young"],
  "边": ["biān", "side; edge"],
  "迎": ["yíng", "to welcome"],
  "远": ["yuǎn", "far"],
  "选": ["xuǎn", "to choose"],
  "释": ["shì", "to explain; to release"],
  "错": ["cuò", "wrong; mistake"],
  "闭": ["bì", "to close"],
  "院": ["yuàn", "courtyard; institution"],
  "除": ["chú", "to remove; except"],
  "险": ["xiǎn", "danger"],
  "难": ["nán", "difficult"],
  "需": ["xū", "to need"],
  "非": ["fēi", "not; wrong"],
  "须": ["xū", "must"],
  "顾": ["gù", "to look after; to consider"],
  "飞": ["fēi", "to fly"],
  "马": ["mǎ", "horse"],
  "麻": ["má", "hemp; numb"]
};
